name: optimizebnb
services:
  - name: web
    github:
      branch: main
      deploy_on_push: true
      repo: yourusername/optimizebnb
    build_command: npm run build
    run_command: npm start
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-s
    routes:
      - path: /
    envs:
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        value: ${OPENAI_API_KEY}
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
        scope: RUN_TIME
        value: ${NEXT_PUBLIC_FIREBASE_API_KEY}
      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        scope: RUN_TIME
        value: ${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
        scope: RUN_TIME
        value: ${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        scope: RUN_TIME
        value: ${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        scope: RUN_TIME
        value: ${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
      - key: NEXT_PUBLIC_FIREBASE_APP_ID
        scope: RUN_TIME
        value: ${NEXT_PUBLIC_FIREBASE_APP_ID}
    health_check:
      http_path: /api/health
      timeout_seconds: 10
    http_options:
      request_timeout_seconds: 300 # Increase request timeout to 5 minutes 